services:
  backend:
    image: stadtkapelle/backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./images:/app/images
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - backend-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge